# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05281eb04a6c81944c8f82d21570bbab"
name = "nodeSApp"
handle = "nodesapp"
application_url = "https://sufficient-appointment-interested-jordan.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://sufficient-appointment-interested-jordan.trycloudflare.com/auth/callback",
  "https://sufficient-appointment-interested-jordan.trycloudflare.com/auth/shopify/callback",
  "https://sufficient-appointment-interested-jordan.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
